import React from "react";
import ReactDOM from "react-dom";
// import App from "./WeatherApp/App.jsx";
// import App from "./React_Router/App";
// import App from "./temp/App";
// import App from "./MusicApp/Play";
// import App from "./MusicApp/App";
import "bootstrap/dist/css/bootstrap.min.css";
import App from "./App";
ReactDOM.render(<App />, document.getElementById("root"));
